# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

inhibit_all_warnings!
use_frameworks!

def common_pods
  pod 'R.swift', '5.0.3'
  pod 'RxSwift', '4.3.1'
  pod 'RxCocoa', '4.3.1'
  pod 'RxSwiftExt', '3.4.0'
  pod 'Alamofire', '4.7.3'
  pod 'AlamofireImage', '3.4.1'
  pod 'SnapKit', '4.2.0'
  pod 'XCGLogger', '6.1.0'
end

workspace 'PhotoViewer.xcworkspace'

target 'photoViewer' do
  
  common_pods

  target 'photoViewerTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
